language: scala
script: sbt scalastyle test
install:
  - wget https://github.com/google/protobuf/releases/download/v2.4.1/protobuf-2.4.1.tar.gz
  - tar -xzvf protobuf-2.4.1.tar.gz
  - pushd protobuf-2.4.1 && ./configure --prefix=/usr && make && sudo make install && popd
scala:
  - 2.12.1
jdk:
  - oraclejdk8
services:
  - rabbitmq
